coin_rooms_TABLE_INFO =
{
	field_sequence =
	{
		[1] = "seat",
		[2] = "name_id",
		[3] = "high",
		[4] = "switch_time",
		[5] = "disable",
		[6] = "pot_round_total",
		[7] = "order",
		[8] = "think_time",
		[9] = "buyin",
		[10] = "mode",
		[11] = "rule",
		[12] = "threshold",
		[13] = "name_pt",
		[14] = "low",
		[15] = "name_en",
		[16] = "sb",
		[17] = "name_es",
		[18] = "pot_times",
		[19] = "name_zh",
		[20] = "name_th",
		[21] = "name",
		[22] = "room_type",
		[23] = "level",
		[24] = "ante",
		[25] = "name_ph",
		[26] = "gold_packge",
		[27] = "id",
		[28] = "pochan_packge",
		[29] = "name_zh_hk",
		[30] = "rake",
		[31] = "custom_id",
		[32] = "name_hi",
		[33] = "name_fr",
	},
}
