item_TABLE_INFO =
{
	-- 最外层的表的顺序
	field_sequence = 
	{
		[1] = "id",
		[2] = "name",
		[3] = "name_zh",
		[4] = "name_en",
		[5] = "name_hi",
		[6] = "name_th",
		[7] = "name_fr",
		[8] = "name_es",
		[9] = "name_id",
		[10] = "name_zh_hk",
		[11] = "name_pt",
		[12] = "name_ph",
		[13] = "item_list",
		[14] = "is_special",
		[15] = "category",
		[16] = "price",
		[17] = "days",
		[18] = "club_count",
		[19] = "room_count",
		[20] = "delay_count",
		[21] = "privilege_data",
		[22] = "other_user_data",
		[23] = "join_club_count",
		[24] = "push_str",
		[25] = "ac_item_list",
		[26] = "disable",
		[27] = "icon_type",
		[28] = "expiration_time",
		[29] = "icon_name",
		[30] = "jump_code",
		[31] = "match_id",
		[32] = "emoji_id",
		[33] = "description_zh",
		[34] = "description_en",
	},
}